defaults:
  deploy_cmd: gem push *.gem
  before_deploy_cmds:
    - /usr/local/bin/op tag-release
    - sed -i "" -e "s/\".*/\"$(git tag| sort -n -t. -k1,1 -k2,2 -k3,3 | tail -1 | sed s/v//)\"/" lib/ical_importer/version.rb
    - git add  lib/ical_importer/version.rb
    - git commit -m "Version Bump" && git push
    - gem build ical_importer.gemspec
  after_deploy_cmds:
    - rm *.gem
environments:
  -
    rubygems: {}
